sampling:
  - layer: 1
    neighbor: 
      - 100
    strategy: 'recent'
    prop_time: False
    history: 1
    duration: 0
    num_thread: 1
memory: 
  - type: 'none'
    dim_out: 0
gnn:
  - arch: 'SLIM'
    layer: 1
    dim_time: 100
    dim_out: 100
    skip_alpha: 1
train:
  - epoch: 100
    batch_size: 600
    lr: 0.001
    dropout: 0.2
    att_dropout: 0.2
    all_on_gpu: True